name: my_health_app
description: "Multilingual mobile health application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^6.1.2
  supabase_flutter: ^2.8.0
  http: ^1.2.1
  table_calendar: ^3.1.2
  intl: 0.20.2
  shared_preferences: ^2.2.3
  uuid: ^4.4.0
  cupertino_icons: ^1.0.8
  flutter_slidable: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/data/
